### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Etiene** [leafo/lua-payments#2]
Hey, leaf! I just found this! Cool libs :D

I might want fork and make a sailor version, or prepare it for a more general lua use, make a rock, etc. 
But first I need to know what the license is, if I can do that, etc. 

Thanks :+1:

**Comment by leafo** [comment]
this project is a long way from any usable state, but it will be MIT when I release it.

**Comment by Etiene** [comment]
ok! thanks :D
